### ISSUE TITLE
RESET button don't work with battery v0.0.8

### ISSUE THREAD

**Issue by ilveropera** [pimoroni/enviro#107]
hi there

Enviro Grow v0.0.8

When Poke is blinking, press RESET button stops the blinking

When there is some error (! blinking) does nothing like in sleep mode.

**Comment by ZodiusInfuser** [comment]
Hi. My understanding is that this is expected behaviour. The (!) LED is not controlled by the Pico, but rather an onboard RTC chip. This means that when there's an error the Pico can tell the RTC to flash the LED, and then it can go back to sleep to save power. This is why the reset doesn't do anything and you need to press poke first. Hope that helps.
